name: Build Dapplo.Confluence

on:
  push:
    branches: [ "*" ]
#  pull_request:
#    branches: [ "master" ]
  workflow_dispatch:

jobs:

  build:

    strategy:
      matrix:
        configuration: [CI]
        dotnetVersion: [6.0.x]

    runs-on: ubuntu-latest  # For a list of available runner types, refer to
                            # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    env:
      SOLUTION_PATH: src/Dapplo.Confluence.sln
      BUILD_PATH: src/Dapplo.Confluence/bin/Release
      NUGET_REPO: https://nuget.pkg.github.com/migueltvms/index.json

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ matrix.dotnetVersion }}
        source-url: ${{ NUGET_REPO }}
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      
    - name: Build
      run: dotnet build $SOLUTION_PATH --configuration $CONFIGURATION
      env:
        CONFIGURATION: ${{ matrix.configuration }}

    - name: Pack
      run: dotnet pack $SOLUTION_PATH --configuration $CONFIGURATION
      env:
        CONFIGURATION: ${{ matrix.configuration }}

    - name: Publish
      run: dotnet nuget push $BUILD_PATH/*.nupkg --skip-duplicate --no-symbols true --api-key ${{ secrets.GITHUB_TOKEN }}
