name: Build

on:
  push:
    branches: [ "*" ]
#  pull_request:
#    branches: [ "master" ]
  workflow_dispatch:

jobs:

  build:

    strategy:
      matrix:
        configuration: [Release]
        dotnetVersion: [6.0.x]

    runs-on: windows-latest  # For a list of available runner types, refer to
                            # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    env:
      SOLUTION_PATH: src/Dapplo.Confluence.sln
      TEST_PATH: src/Dapplo.Confluence.Tests/Dapplo.Confluence.Tests.csproj                      
      
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ matrix.dotnetVersion }}

    - name: Restore Packages
      run: dotnet restore $env:SOLUTION_PATH
      
    - name: Build
      run: dotnet build $env:SOLUTION_PATH --configuration $env:CONFIGURATION
      env:
        CONFIGURATION: ${{ matrix.configuration }}

    # Restore the application to populate the obj folder with RuntimeIdentifiers
    #- name: Restore the application
    #  run: msbuild $env:solution_path /t:Restore /p:Configuration=$env:Configuration
    #  
