name: Build Dapplo.Confluence

on:
  push:
    branches: [ "*" ]
#  pull_request:
#    branches: [ "master" ]
  workflow_dispatch:

jobs:

  build:

    strategy:
      matrix:
        configuration: [CI]
        dotnetVersion: [6.0.x]

    runs-on: ubuntu-latest  # For a list of available runner types, refer to
                            # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    env:
      SOLUTION_PATH: src/Dapplo.Confluence.sln
      BUILD_PATH: src/Dapplo.Confluence/bin/Release

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ matrix.dotnetVersion }}
      
    - name: Build
      run: dotnet build $SOLUTION_PATH --configuration $CONFIGURATION
      env:
        CONFIGURATION: ${{ matrix.configuration }}

    - name: Pack
      run: dotnet pack $SOLUTION_PATH --configuration $CONFIGURATION
      env:
        CONFIGURATION: ${{ matrix.configuration }}

    - name: Prepare Package Source
      run: dotnet nuget add source --username ${{ github.repository_owner }} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json

    - name: Publish
      run: dotnet nuget push $BUILD_PATH/*.nupkg --source "github" --api-key ${{ secrets.NUGET_PAT }}
